# You can set this to a region that is geographically close to you
ENV["AWS_DEFAULT_REGION"] = "us-west-2"

# This lets the user know how to install the plugin
if !Vagrant.has_plugin?("vagrant-ec2-metadata")
  puts "Please install the vagrant-ec2-metadata plugin:"
  puts
  puts "    vagrant plugin install vagrant-ec2-metadata"
  puts
  exit 0
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ec2-metadata-example"

  # Put these lines above other provisioners that need to use the credentials
  # Don't forget to start the server first with "vagrant ec2-metadata"
  config.ec2_metadata.profile = "default"
  # config.ec2_metadata.role_arn = "arn:aws:iam::123456789012:role/ReadOnlyRole"
  config.vm.provision "ec2-metadata", run: "always"

  # Print our AWS identity inside of the VM
  config.vm.provision "shell", inline: <<~SCRIPT
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y python3-pip
    pip3 install -U awscli
  SCRIPT
  config.vm.provision "shell", inline: "aws sts get-caller-identity || exit 0", run: "always"
end
